### ISSUE TITLE
Deforum Cadence Default Workflow not working with Stable Diffusion 3.5 Image model

### ISSUE THREAD

**Issue by ShantanuVidwans** [XmYx/deforum-comfy-nodes#66]
Steps to reproduce:
1)Mostly default configurations in ComfyUI
2)Have sd3.5_medium.safetensors model in models/checpoints in comfyui
3)Set Load Checkpoint ckpt_name attribute to sd 3.5 model

When Running the workflow i get this error:

`! 'NoneType' object has no attribute 'tokenize'
2025-03-02 17:48:25.642 - execution.py:397 - ERROR - Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/nodes/deforum_cond_nodes.py", line 30, in fn
    n_cond = self.get_conditioning(prompt=negative_prompt, clip=clip)
  File "/root/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/nodes/deforum_cond_nodes.py", line 64, in get_conditioning
    tokens = clip.tokenize(prompt)
AttributeError: 'NoneType' object has no attribute 'tokenize'`

If i have stable diffusion sdxl model or the model that is set as default (realismEngineSDXL) in the workflow, it does work as expected
